### ISSUE TITLE
Different output than PuttyGen

### ISSUE THREAD

**Issue by frankhommers** [akira345/pem2ppk#1]
When I use a PEM with just one "-----BEGIN RSA PRIVATE KEY-----" it won't generate a correct .PPK.
The server rejects the key.

If I generate the ppk with puttygen.exe it works. Any ideas?

**Comment by akira345** [comment]
Hi.
The conversion part of this program uses the following code.
https://antonymale.co.uk/generating-putty-key-files.html

It may be a problem with this code.
In that case, I will not be able to fix this code. Because I can not understand this code…

I have generated the key with the following contents, which is going well.

`ssh-keygen -t rsa -b 4096 -f ./test.pem`

I use connection software TeraTerm and tested server UbuntuServer 16.04.

(I am not good at English. I happy to your message.)

**Comment by frankhommers** [comment]
Hi Akira,

Check these files out out:

Input Private Key: [rsa private key.pem.txt](https://github.com/akira345/pem2ppk/files/2103490/rsa.private.key.pem.txt)

Output from PuttyGen: [puttygen.ppk.txt](https://github.com/akira345/pem2ppk/files/2103489/puttygen.ppk.txt)

Output from your code (different and wrong): [pem2ppk_code.ppk.txt](https://github.com/akira345/pem2ppk/files/2103491/pem2ppk_code.ppk.txt)

Public Key (For reference): [public key.pem.txt](https://github.com/akira345/pem2ppk/files/2103488/public.key.pem.txt)

**Comment by akira345** [comment]
Hi .
I was late reply. sorry. I'm too busy work ....

I got your same file, set it on my test server and tried ssh connection.

On my test server, both of them succeeded. Both files is puttygen.ppk.txt and pem2ppk_code.ppk.txt.

My test server is CentOS Linux release 7.3.1611. I use SSH Client Software is [TeraTerm](https://ja.osdn.net/projects/ttssh2/releases/).
The procedure I tried is as follows.

1:Download same files(rsa.private.key.pem.txt、puttygen.ppk.txt、pem2ppk_code.ppk.txt)
2:Convert rsa.private.key.pem.txt and set authorized_keys.
``ssh-keygen -y -f rsa.private.key.pem.txt > ~/.ssh/authorized_keys``
`` chmod 0600 ~/.ssh/authorized_keys``
3:I attempted to connect to the test server using the rsa.private.key.pem.txt key or the puttygen.ppk.txt key or the pem2ppk_code.ppk.txt key. I used TeraTerm.
4:I also tried using rsa.private.key.pem.txt again convert with pem2ppk.
In all I was able to connect with SSH.
